# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.22
# 
# >> macros
# << macros

Name:       ltrace
Summary:    ltrace intercepts and records dynamic library calls
Version:    0.7.2
Release:    1
Group:      Development Platform/Platform SDK
License:    GPL v2
URL:        git://git.debian.org/git/collab-maint/ltrace.git
Source0:    ltrace-%{version}.tar.gz
Source100:  ltrace.yaml
BuildRequires:  pkgconfig(glib-2.0)
BuildRequires:  binutils-devel
BuildRequires:  elfutils-devel


%description
ltrace intercepts and records dynamic library calls which are called by an executed process and the signals received by that process. It can also intercept and print the system calls executed by the program.




%prep
%setup -q -n src
%autogen

# >> setup
# << setup

%build
# >> build pre
# << build pre

%configure --disable-static
make %{?jobs:-j%jobs}

# >> build post
# << build post
%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%make_install

# >> install post
# << install post






%files
%defattr(-,root,root,-)
# >> files
%{_bindir}
%{_mandir}
%{_docdir}
%{_sysconfdir}
# << files


